### PR TITLE
feat: add message-skipped input to action

### PR DESCRIPTION
**Pull request by aryella-lacerda**
### The Context

So this is my use case: I want to post a comment on a PR with the result of our E2E tests, which run on a separate repo. 

In the E2E tests repo:

```
  run-tests:
    if:                                      # run condition
    runs-on: ubuntu-latest
    steps:
      ...

  communicate-with-origin-pr:
    if: always()
    needs: run-tests
    runs-on: ubuntu-latest
    steps:
      - name: Post PR comment with Final Status
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.actions.createWorkflowDispatch({
              inputs: {
                "status": "${{ needs.run-tests.result }}",     <--------
                ...
              }
            })
```

The result of my `run-tests` job is eventually passed along to this action. The `run-tests` job may pass, fail, be cancelled, or get skipped in certain situations. There's also a fifth "started" status that I use to indicate that we don't yet know what the test results are.

The "started" status triggers the default `message` for this action. I use message overrides for the success, failure, and cancellation cases. 

### The Problem

But in the event that the tests are skipped, this action defaults to the `message` input, which doesn't fit the situation.

### The Solution?

I added a fourth message override for the skipped status.

### CODE REVIEW

**Review by mshick — APPROVED** [review]
Smart! If you can fix the conflict I'll merge this right away. Thank you for the PR.

**Comment by aryella-lacerda** [comment]
Merge conflict fixed! 😁

**Comment by mshick** [comment]
@aryella-lacerda Thanks! Doing a test run, will merge shortly.

**Comment by aryella-lacerda** [comment]
Linting issue fixed! I'm not sure what the problem with the build step was, though 🤔

**Comment by mshick** [comment]
@aryella-lacerda I think it's an issue introduced in a recent merge. I'll merge yours and get the tests passing again. Thanks for the contribution!

**Pull request merged**
