### PR TITLE
allow message-{success, failure, cancelled} to take precedent over message-path

### PR DESCRIPTION
**Pull request by twang817**
This defers the evaluation of `message` and `message-path` until `message-success`, `message-failure`, and `message-cancelled` has had a chance to run.  If any of these values have set `message`, we do not bother loading `message-path`.

This allows us to write workflows that look like this:

```yaml
name: Commit Lint

on:
  pull_request:

permissions:
  contents: read
  pull-requests: write

jobs:
  commitlint:
    name: commitlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run commitlint
        id: commitlint
        uses: ahmadnassri/action-commit-lint@v2

      - name: Report to data file
        if: failure()
        run: |
          echo '{"report": ${{ steps.commitlint.outputs.report }}}' > .github/commitlint-data.json

      - name: Render comment template
        uses: cuchi/jinja2-action@v1.2.0
        if: failure()
        with:
          template: .github/commitlint-comment.md.j2
          data_file: .github/commitlint-data.json
          output_file: .github/commitlint-comment.md
          strict: true

      - name: Comment on PR
        uses: twang817/add-pr-comment@v1 # <- this would be mshicks/add-pr-comment@v2 after merge
        if: always()
        with:
          message-id: commitlint
          message-path: .github/commitlint-comment.md
          message-success: "All commit messages :white_check_mark:"
```

Here, we see that we can the message on a successful run directly in `message-success` and not worry over the fact that our `message-path` is invalid.

### CODE REVIEW

**Comment by twang817** [comment]
I believe this addresses #75

**Comment by mshick** [comment]
@twang817 Thanks for the PR! Do you mind resolving the conflicts and I'll take a look?

**Comment by twang817** [comment]
@mshick Resolved.  You'll probably want to make sure you run npm run build to make sure that the generated files are correct.

**Comment by mshick** [comment]
@twang817 This makes sense to me. There have been some changes to the repo since you opened this — do you mind fixing the conflicts and making any necessary updates and I'll get this reviewed right away? Thanks for you PR!

**Comment by mshick** [comment]
I believe I've now incorporated your key change into the recent minor refactor I did. Thanks for bringing this issue to me, it's really the reason I made the change, so happy to add you as a contributor. I appreciate the PR!

Feel free to open a new issue if you feel like I missed something.

@all-contributors add @twang817 for code

**Pull request closed without merging**
